import Document, { DocumentContext, Html,  Main, NextScript, Head  } from 'next/document';


import Navbar from '../components/navbar';
import Footer from '../components/footer';

class MyDocument extends Document {
  static async getInitialProps(ctx: DocumentContext) {
    const initialProps = await Document.getInitialProps(ctx)

    return initialProps
  }

  render() {
      return <Html>
          <Head >
            <meta name="description" content="Generated by Nearbay" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <body>
              <Navbar />
              <Main />
              <NextScript />
              <Footer />
          </body>
      </Html>
  }
}

export default MyDocument