import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Footer from "../components/footer";
import Navbar from "../components/navbar";

import ProductCard from "../components/product_card";

const Home: NextPage = () => {
  return (
    <div className="w-100 flex flex-col items-center">
      <Head>
        <title>Nearbay.</title>
        <meta name="description" content="Generated by Nearbay" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="container content-center w-full m-0">

        <p className={styles.description}>
          A marketplace which is secured by
          <code className={styles.code}>Near Blockchain.</code>
        </p>

        <div className="grid grid-cols-3 gap-4">
          <ProductCard />
        </div>
      </main>

      
      <Footer />
    </div>
  );
};

export default Home;
